### PR TITLE
Resolves issue #38

### LINKED ISSUE #38: Package amphp/artax is abandoned, you should avoid using it. Use amphp/http-client instead.
When I use `composer install` on this repository, I get following message:

```Bash
Package amphp/artax is abandoned, you should avoid using it. Use amphp/http-client instead.
```

### PR DESCRIPTION
**Pull request by peter279k**
Closes #38.

### CODE REVIEW

**Comment by lyrixx** [comment]
How, that was super simple!
Thanks a lot for your first PR

**Comment by kelunik** [comment]
Too simple. While the 3.x tags exist in that package, they shouldn't be used. For 3.x you should still use the old package name.

**Comment by peter279k** [comment]
Perhaps we can consider upgrading to `^4.x` version?

**Comment by kelunik** [comment]
^ exactly that.

**Comment by lyrixx** [comment]
Do someone want to try to upgrade?

**Comment by peter279k** [comment]
Don't worry about it.

I will do that 😉.

**Comment by peter279k** [comment]
Just notice that it's the breaking change after we want to upgrade to `amphp/http-client` package.

After upgrading the `amphp/http-client` to `^4.0` version, it seems that it will throw `Error: Class 'Amp\Artax\DefaultClient' not found` during the smoke testing.

@kelunik, do you have any idea about this? Can you provide the migrating guide about `amphp/http-client` version upgrading?
@lyrixx, do you want to do this change?

**Pull request merged**
